#ifndef MDIO_INTERFACE_H
#define MDIO_INTERFACE_H
/***********macro decleration************/
#define MASKING_ONE_BITS  		 0b1
#define MASKING_TWO_BITS  		 0b11
#define MASKING_THREE_BITS		 0b111
#define MASKING_FOUR_BITS 		 0b1111
#define MASKING_FIVE_BITS	 	 0b11111
#define MASKING_SIX_BITS	 	 0b111111
#define MASKING_SEVEN_BITS 		 0b1111111
#define MASKING_EIGHT_BITS 		 0b11111111
#define MASKING_NINE_BITS 		 0b111111111
#define MASKING_TEN_BITS 		 0b1111111111
#define MASKING_ELEVEN_BITS 	 0b11111111111
#define MASKING_TWELEVE_BITS	 0b111111111111
#define MASKING_THIRTEEN_BITS	 0b1111111111111

/***************data type section************/
typedef enum
{
GPIO_PORTA,
GPIO_PORTB,
GPIO_PORTC,
}EN_GPIO_PORT_NO_T;
typedef enum
{
GPIO_PIN0=0,
GPIO_PIN1,
GPIO_PIN2,
GPIO_PIN3,
GPIO_PIN4,
GPIO_PIN5,
GPIO_PIN6,
GPIO_PIN7,
GPIO_PIN8,
GPIO_PIN9,
GPIO_PIN10,
GPIO_PIN11,
GPIO_PIN12,
GPIO_PIN13,
GPIO_PIN14,
GPIO_PIN15,
}EN_GPIO_PIN_NO_T;
typedef enum
{
GPIO_MODE_INPUT=0,
GPIO_MODE_OUTPUT,
GPIO_MODE_ALTERNATIVE,
GPIO_MODE_ANALOG,
}EN_GPIO_MODE_T;
typedef enum
{
GPIO_OTYPE_PUSH_PULL=0,
GPIO_OTYPE_OPEN_DRAIN,
}EN_GPIO_OTYPE_T;
typedef enum
{
GPIO_OSPEED_LOW,
GPIO_OSPEED_MEDIUM,
GPIO_OSPEED_HIGH,
GPIO_OSPEED_VERY_HIGH,
}EN_GPIO_OSPEED_T;
typedef enum
{
GPIO_NOT_PULLED,
GPIO_PUPD_PULL_UP,
GPIO_PUPD_PULL_DOWN,
}EN_GPIO_PUPD_T;
typedef enum
{
GPIO_LOGIC_LEVEL_LOW,
GPIO_LOGIC_LEVEL_HIGH,
}EN_GPIO_LOGICLEVEL_T;
/**************FUNCTION DECLERATION**********/
void MGPIO_voidSetPinMode(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_MODE_T Mode);
void MGPIO_voidSetPinOType(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_OTYPE_T Otype);
void MGPIO_voidSetPinOSpeed(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_OSPEED_T OSpeed);
void MGPIO_voidSetPinPUPD(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_PUPD_T PUPD);
void MGPIO_voidGetPinValue(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_LOGICLEVEL_T *Value);
void MGPIO_voidSetPinValue(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_LOGICLEVEL_T Value);
void MGPIO_voidSetPinInput(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_OSPEED_T OSpeed,EN_GPIO_MODE_T Mode,EN_GPIO_PUPD_T PUPD);
void MGPIO_voidSetPinOutput(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo,EN_GPIO_OSPEED_T OSpeed,EN_GPIO_OTYPE_T Otype,EN_GPIO_PUPD_T PUPD);
void MGPIO_WRITE_NUMBER_OF_BITS(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T Start_Bit,u8 Masked_val_of_Bits,u32 Value);
void MGPIO_voidTogglePinValue(EN_GPIO_PORT_NO_T PortNo,EN_GPIO_PIN_NO_T PinNo);

#endif //MDIO_INTERFACE_H
