#ifndef MRCC_CONFIG_H
#define MRCC_CONFIG_H

/*Three Main Clock Sources:
 * 1-HSI_CLOCK_SOURCE
 * 2-HSE_CLOCK_SOURCE
 * 3-PLL_HSI_CLOCKED_PLL
 * 4-PLL_HSE_CLOCKED_PLL
 */
#define RCC_CLOCK_SOURCE_TYPE   HSI_CLOCK_SOURCE

/*Two clock signal generator for HSE
 * Options:-
 * 1-HSE_EXTERNAL_CRYSTAL_CERAMIC_RESENATOR_CLOCK_SIGNAL
 * 2-HSE_EXTERNAL_USER_CLOCK_SIGNAL
 * */

#define HSE_CLOCK_SIGNAL_GENERATOR   HSE_EXTERNAL_CRYSTAL_CERAMIC_RESENATOR_CLOCK_SIGNAL
/*Main PLL IS DRIVED BY HSE OR HSI
 * Options:-
 * 1-PLL_HSI_CLOCKED_PLL
 * 2-PLL_HSE_CLOCKED_PLL*/
#define RCC_PLL_CLOCK_SOURCE         PLL_HSE_CLOCKED_PLL

/*PLL CONFIGURATIONS PARAMETERS
 * 1-PLL_N_MULTIPLICATION_FACTOR
 * 2-PLL_M_DIVISION_FACTOR
 * 3-PLL_P_DIVISION_FACTOR*/


/*SELECT P DIV FACTOR
 * value must be 2 , 4, 6 ,8*/
#define PLL_P_DIVISION_FACTOR     (8)


/*SELECT N MULTIPLICATION FACTOR
 * value must be From 192 - > 432*/
#define PLL_N_MULTIPLICATION_FACTOR     (432)



/*SELECT M DIVISION FACTOR
 * value must be From 192 - > 432*/
#define PLL_M_DIVISION_FACTOR    		 (2)

/*SELECT Q DIVISION FACTOR
 * value must be From 2 - > 15*/
#define PLL_Q_DIVISION_FACTOR    		 (15)

/*SELECT AHB PRESCALER *
 *1-SYSTEM_CLOCK_NOT_DIVIDED
 *2-SYSTEM_CLOCK_DIV_002
 *3-SYSTEM_CLOCK_DIV_004
 *4-SYSTEM_CLOCK_DIV_008
 *5-SYSTEM_CLOCK_DIV_016
 *6-SYSTEM_CLOCK_DIV_064
 *7-SYSTEM_CLOCK_DIV_128
 *8-SYSTEM_CLOCK_DIV_256
 *9-SYSTEM_CLOCK_DIV_512
 *
 */
#define RCC_AHB_PRESCALER    SYSTEM_CLOCK_DIV_016



/*SELECT ABP1 PRESCALER *
 *1-AHB_CLOCK_NOT_DIVIDED
 *1-AHB_CLOCK_DIV_02
 *1-AHB_CLOCK_DIV_04
 *1-AHB_CLOCK_DIV_08
 *1-AHB_CLOCK_DIV_16
 *
 */
#define RCC_ABP1_PRESCALER   AHB_CLOCK_DIV_16


/*SELECT ABP2 PRESCALER *
 *1-AHB_CLOCK_NOT_DIVIDED
 *1-AHB_CLOCK_DIV_02
 *1-AHB_CLOCK_DIV_04
 *1-AHB_CLOCK_DIV_08
 *1-AHB_CLOCK_DIV_16
 *
 */
#define RCC_ABP2_PRESCALER   AHB_CLOCK_DIV_16


#endif // MRCC_CONFIG_H
